pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

include ':FtcRobotController'
include ':TeamCode'

if (file('../Volt').exists()) {
    includeBuild('../Volt') {
        dependencySubstitution {
            substitute module('com.github.KingsSack:volt') using project(':Volt')
        }
    }
}
