<script lang="ts">
  import { editorState } from '$lib/states/editor.svelte';
  import { uiState } from '$lib/states/ui.svelte';
  import { fly } from 'svelte/transition';

  async function copyCode() {
    if (editorState.generatedCode) {
      await navigator.clipboard.writeText(editorState.generatedCode);
      uiState.addToast('Code copied to clipboard', 'success');
    }
  }
</script>

{#if uiState.showCodeModal}
  <div
    class="fixed inset-0 z-110 flex items-center justify-center bg-black/80 backdrop-blur-sm"
    transition:fly
  >
    <div
      class="flex max-h-[85vh] w-full max-w-4xl flex-col overflow-hidden rounded-3xl border border-gray-800 bg-gray-900 shadow-2xl"
    >
      <div
        class="flex items-center justify-between border-b border-gray-800 bg-linear-to-r from-green-600/20 to-emerald-600/20 p-6"
      >
        <div>
          <h2 class="flex items-center text-xl font-bold">
            <svg
              class="mr-2 h-6 w-6 text-green-400"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4"
              />
            </svg>
            Generated Code
          </h2>
          <p class="mt-1 text-sm text-gray-400">Kotlin OpMode code generated from your flow</p>
        </div>
        <div class="flex space-x-2">
          <button
            onclick={copyCode}
            class="flex items-center rounded-xl bg-gray-800 px-4 py-2 text-sm font-medium transition-all hover:bg-gray-700"
          >
            <svg class="mr-2 h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"
              />
            </svg>
            Copy
          </button>
          <button
            onclick={() => uiState.closeCodeModal()}
            class="rounded-xl p-2 text-gray-400 transition-all hover:bg-gray-800 hover:text-white"
            aria-label="Close"
          >
            <svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M6 18L18 6M6 6l12 12"
              />
            </svg>
          </button>
        </div>
      </div>

      <div class="flex-1 overflow-auto p-6">
        <pre
          class="overflow-auto rounded-2xl border border-gray-800 bg-gray-950 p-6 font-mono text-sm leading-relaxed text-gray-300">
					<code>{editorState.generatedCode}</code>
				</pre>
      </div>

      <div class="border-t border-gray-800 bg-gray-900/50 p-4 text-center text-xs text-gray-500">
        This code was auto-generated by Volt Flow Editor. Copy it to your TeamCode project.
      </div>
    </div>
  </div>
{/if}
