title: HootAndCompute Documentation
description: >-
  The docs for the 24123, HootAndCompute FTC team.
domain: kingssack.github.io      # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://kingssack.github.io # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /HootAndCompute/docs/   # place folder name if the site is served in a subfolder
theme: jekyll-theme-architect
remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
