site_name: HootAndCompute Documentation'
site_url: https://kingssack.github.io/hootandcompute/
nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started
    - Creating an Attachment: attachments/creating-an-attachment
  - API Reference:
    - TeamCode: kdoc/teamcode
    - Volt: kdoc/volt
theme:
  name: readthedocs
  highlightjs: true
  hljs_langauges:
    - kotlin
    - java
    - groovy