name: Test TeamCode Android APK

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'corretto'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build TeamCode APK
      run: ./gradlew assembleRelease -Pmodule=TeamCode
    - name: Deploy TeamCode APK
      run: |
        adb install -r app/build/outputs/apk/release/TeamCode-release.apk
        if [ $? -ne 0 ]; then
          echo "Error installing TeamCode APK"
          exit 1
        fi
